# Site settings
title: "namedLambda"
email: haasis_noah@yahoo.de
description: > # this means to ignore newlines until "baseurl:"
  namedLambda &copy 2018 - Explore new ideas
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://noahhaasis.github.io" # the base hostname & protocol for your site
twitter_username: haasis_noah
github_username:  noahhaasis

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: rounge

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed
